#!/usr/bin/env python2
""" This program parses, through stdin, a file containing multiple
choice questions and answers. Each question is expected to have four
possible answers, with the first question being the correct one. The
input file is expected to be in the following format: each question
and its answers are separated by a single line break, and new question
is preceded by two line breaks.

Question set format:

question
correct answer
answer
answer
answer

WARNING: Any question that is not followed by four non-whitespace-only
lines will be discarded. An error message will be sent to stderr with
the line number of the improperly formatted question set.

"""
from __future__ import division, print_function
import sys

def question_set(FILE):
    """ This function reads a file and yields a question and its four
    answers in a set (question, correct_answer, answer1, answer2,
    answer3), one at a time until it reaches the end of file.
    """
    question_set = []         # question_set contains a question and
                              # its four answers in the order
                              # (question, correct_answer, answer1,
                              # answer2, answer3)

    linenum = 0               # linenum keeps track the line number
                              # of the line currently being parsed.

    q_linenum = 0             # line number before the most recently
                              # parsed question

    for line in FILE:
        linenum += 1
        if line.isspace() and len(question_set) == 5:
            q_linenum = linenum + 1
            yield question_set
            question_set = []
        elif line.isspace() and len(question_set) != 5:
            print("\n\nERROR: the question at line {} "
                  "does not have exactly four "
                  "answers.\n\n".format(q_linenum), file=sys.stderr)
            question_set = [] 
        else:
            question_set.append(line.rstrip())

    # Print last question set.
    if len(question_set) == 5:
        yield question_set
    else:
        exit("\n\nERROR: the last question in the input file "
             "does not have exactly four answers.\n\n")

for (q, correct_answer, answer1, answer2, answer3) in question_set(sys.stdin):
    print("{}\n* {}\n  {}\n  {}\n  {}".format(q, correct_answer, answer1,
                                              answer2, answer3),
          file=sys.stdout)
